In [1]:
import numpy as np

# Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5
       )

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5,6,8,87])
a

array([ 1,  2,  3,  4,  5,  6,  8, 87])

Accessing elements of the array

In [7]:
a[0]

1

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
 np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dementional Arrays

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
n[:,2]

array([3, 6, 9])

# Randomly Generated arrays

In [17]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [18]:
#rand numbers from normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [20]:
#generate random integers
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Elemets wise Operations

In [22]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a+1

array([1, 2, 3, 4, 5])

In [24]:
a*2

array([0, 2, 4, 6, 8])

In [30]:
b= np.arange(5)
b

array([0, 1, 2, 3, 4])

In [31]:
a+b

array([0, 2, 4, 6, 8])

In [38]:
a[0]=1
b/a

array([0., 1., 1., 1., 1.])

# Summarizing operations

In [39]:
a

array([1, 1, 2, 3, 4])

In [40]:
a.min()

1

In [41]:
a.sum()

11

In [42]:
a.mean()

2.2

In [43]:
#standard deviation 
a.std()

1.16619037896906

In [ ]:
#define the vector vector multiplication function 
def vector_vector_multipication (u,v):
    assert u.shape[0]=v.shape[0]
    n=u.shape[0]
    result=0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

#define the matrix vector multiplication function 
def matrix_vector_muliplication (U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i]=vector_vector_muliplication(U[i],v)
        
    return result